name: Setup .NET Runtime Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Ensure to use the required .NET SDK version

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build the repository
        run: |
          dotnet build --configuration Release

      - name: Run tests
        run: |
          dotnet test --configuration Release --no-build --verbosity normal